baseURL = "https://jaredwheeler23.github.io/wheelerworldkitchen/"
languageCode = "en-us"
title = "Wheeler World Kitchen"
theme = "PaperMod"

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Our Story"
url = "/story/"
weight = 2

[[menu.main]]
name = "Recipes"
url = "/recipes/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[markup.goldmark.renderer]
unsafe = true